"""image_dimensions

Revision ID: 1583b6051cda
Revises: 9a5d511052bf
Create Date: 2026-05-06 16:21:42.881460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1583b6051cda'
down_revision: Union[str, Sequence[str], None] = '9a5d511052bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_height', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('image_height')
        batch_op.drop_column('image_width')

    # ### end Alembic commands ###
