"""perf_index_source_lastseen

Revision ID: 7115a83cd62f
Revises: 1583b6051cda
Create Date: 2026-06-12 09:11:49.635559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7115a83cd62f'
down_revision: Union[str, Sequence[str], None] = '1583b6051cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_event_source_lastseen', ['source_id', 'last_seen_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_event_source_lastseen')

    # ### end Alembic commands ###
