"""user_roles_and_allowed_media

Revision ID: 84dd9359d858
Revises: b0639d9662c3
Create Date: 2026-04-20 14:06:58.121417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dd9359d858'
down_revision: Union[str, Sequence[str], None] = 'b0639d9662c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='admin'))
        batch_op.add_column(sa.Column('allowed_media', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allowed_media')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
