"""initial_schema

Revision ID: b0639d9662c3
Revises: 
Create Date: 2026-04-20 12:49:15.919695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0639d9662c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_outlets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('regions', sa.Text(), nullable=True),
    sa.Column('drupal_api_url', sa.String(length=500), nullable=True),
    sa.Column('drupal_api_key', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('events_found', sa.Integer(), nullable=True),
    sa.Column('events_new', sa.Integer(), nullable=True),
    sa.Column('events_updated', sa.Integer(), nullable=True),
    sa.Column('events_duplicate', sa.Integer(), nullable=True),
    sa.Column('events_marked_stale', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_logs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_logs_started_at'), ['started_at'], unique=False)

    op.create_table('source_health',
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('parser_type', sa.String(length=50), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.DateTime(), nullable=True),
    sa.Column('last_error_msg', sa.Text(), nullable=True),
    sa.Column('last_events_found', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('total_events_7d', sa.Integer(), nullable=True),
    sa.Column('avg_events', sa.Float(), nullable=True),
    sa.Column('avg_duration_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('last_retry_count', sa.Integer(), nullable=True),
    sa.Column('list_url', sa.String(length=1000), nullable=True),
    sa.Column('feed_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('unprocessed_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('page_title', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unprocessed_urls', schema=None) as batch_op:
        batch_op.create_index('idx_unprocessed_source', ['source_id'], unique=False)
        batch_op.create_index('idx_unprocessed_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('time_start', sa.String(length=20), nullable=True),
    sa.Column('time_end', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('price', sa.String(length=200), nullable=True),
    sa.Column('organizer', sa.String(length=300), nullable=True),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('categories', sa.String(length=500), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('image_source', sa.String(length=20), nullable=True),
    sa.Column('description_source', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('detail_url', sa.String(length=1000), nullable=True),
    sa.Column('ticket_url', sa.String(length=1000), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_edited_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_event_id', name='uq_source_event')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_event_active_date', ['is_active', 'date_start'], unique=False)
        batch_op.create_index('idx_event_date', ['date_start'], unique=False)
        batch_op.create_index('idx_event_dedup', ['dedup_hash'], unique=False)
        batch_op.create_index('idx_event_source_active', ['source_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_dedup_hash'), ['dedup_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_source_id'), ['source_id'], unique=False)

    op.create_table('dedup_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incoming_title', sa.String(length=500), nullable=False),
    sa.Column('incoming_source_id', sa.String(length=50), nullable=True),
    sa.Column('incoming_date', sa.Date(), nullable=True),
    sa.Column('incoming_time', sa.String(length=10), nullable=True),
    sa.Column('incoming_location', sa.String(length=500), nullable=True),
    sa.Column('matched_event_id', sa.Integer(), nullable=True),
    sa.Column('matched_title', sa.String(length=500), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dedup_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dedup_decisions_created_at'), ['created_at'], unique=False)

    op.create_table('drupal_push_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=50), nullable=False),
    sa.Column('drupal_nid', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media_outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drupal_push_logs', schema=None) as batch_op:
        batch_op.create_index('idx_push_event', ['event_id'], unique=False)
        batch_op.create_index('idx_push_media', ['media_id'], unique=False)

    op.create_table('event_edits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_edits', schema=None) as batch_op:
        batch_op.create_index('idx_edit_event_time', ['event_id', 'created_at'], unique=False)
        batch_op.create_index('idx_edit_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_edits_event_id'), ['event_id'], unique=False)

    op.create_table('event_media',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('editor_notes', sa.Text(), nullable=True),
    sa.Column('drupal_nid', sa.Integer(), nullable=True),
    sa.Column('drupal_status', sa.String(length=20), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('skipped_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media_outlets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skipped_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'media_id')
    )
    with op.batch_alter_table('event_media', schema=None) as batch_op:
        batch_op.create_index('idx_em_media_status', ['media_id', 'status'], unique=False)
        batch_op.create_index('idx_em_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_media', schema=None) as batch_op:
        batch_op.drop_index('idx_em_status')
        batch_op.drop_index('idx_em_media_status')

    op.drop_table('event_media')
    with op.batch_alter_table('event_edits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_edits_event_id'))
        batch_op.drop_index('idx_edit_user')
        batch_op.drop_index('idx_edit_event_time')

    op.drop_table('event_edits')
    with op.batch_alter_table('drupal_push_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_push_media')
        batch_op.drop_index('idx_push_event')

    op.drop_table('drupal_push_logs')
    with op.batch_alter_table('dedup_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dedup_decisions_created_at'))

    op.drop_table('dedup_decisions')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_source_id'))
        batch_op.drop_index(batch_op.f('ix_events_region'))
        batch_op.drop_index(batch_op.f('ix_events_is_active'))
        batch_op.drop_index(batch_op.f('ix_events_dedup_hash'))
        batch_op.drop_index('idx_event_source_active')
        batch_op.drop_index('idx_event_dedup')
        batch_op.drop_index('idx_event_date')
        batch_op.drop_index('idx_event_active_date')

    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('unprocessed_urls', schema=None) as batch_op:
        batch_op.drop_index('idx_unprocessed_status')
        batch_op.drop_index('idx_unprocessed_source')

    op.drop_table('unprocessed_urls')
    op.drop_table('source_health')
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_logs_started_at'))
        batch_op.drop_index(batch_op.f('ix_scrape_logs_source_id'))

    op.drop_table('scrape_logs')
    op.drop_table('media_outlets')
    # ### end Alembic commands ###
