"""scrape_log_session_id

Revision ID: d20bcf710d05
Revises: 3d413664ff80
Create Date: 2026-04-21 11:24:00.479222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20bcf710d05'
down_revision: Union[str, Sequence[str], None] = '3d413664ff80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_scrape_logs_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_logs_session_id'))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
